
import React, { useState, useEffect } from 'react';
import { 
  LayoutGrid, 
  Plus, 
  Settings as SettingsIcon, 
  Eye, 
  Database, 
  FileText, 
  Share2, 
  HelpCircle,
  Menu,
  ChevronRight,
  Monitor,
  Smartphone,
  Tablet,
  Download,
  Upload as UploadIcon,
  Trash2,
  SlidersHorizontal
} from 'lucide-react';
import { FormConfig, FormField, FieldType, FormPage, FormEntry } from './types';
import BuilderSidebar from './components/Builder/Sidebar';
import BuilderCanvas from './components/Builder/Canvas';
import FieldProperties from './components/Builder/FieldProperties';
import FormPreview from './components/Preview/FormPreview';
import DashboardEntries from './components/Dashboard/EntryViewer';
import Analytics from './components/Dashboard/Analytics';
import FormSettings from './components/Dashboard/FormSettings';

const INITIAL_FORM: FormConfig = {
  id: 'form-' + Math.random().toString(36).substr(2, 9),
  title: 'Untitled Form',
  description: 'Welcome to your new Eagle Form. Start by dragging fields into the canvas.',
  pages: [
    {
      id: 'page-1',
      title: 'Page 1',
      fields: []
    }
  ],
  submitButtonText: 'Submit',
  confirmMessage: 'Thank you for your submission!',
  pdfConfig: {
    headerText: 'Eagle Form Submission Report',
    footerText: 'Generated by Eagle Form Builder',
    includeSubmissionDate: true,
    paperSize: 'a4',
    showLogo: false
  }
};

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<'build' | 'preview' | 'entries' | 'analytics' | 'settings'>('build');
  const [form, setForm] = useState<FormConfig>(INITIAL_FORM);
  const [selectedFieldId, setSelectedFieldId] = useState<string | null>(null);
  const [previewDevice, setPreviewDevice] = useState<'desktop' | 'tablet' | 'mobile'>('desktop');
  const [entries, setEntries] = useState<FormEntry[]>([]);
  const [isSidebarOpen, setIsSidebarOpen] = useState(true);

  // Load from local storage on mount
  useEffect(() => {
    const savedForm = localStorage.getItem('eagle_form_config');
    const savedEntries = localStorage.getItem('eagle_form_entries');
    if (savedForm) setForm(JSON.parse(savedForm));
    if (savedEntries) setEntries(JSON.parse(savedEntries));
  }, []);

  // Auto-save form
  useEffect(() => {
    localStorage.setItem('eagle_form_config', JSON.stringify(form));
  }, [form]);

  const handleAddField = (type: FieldType) => {
    const newField: FormField = {
      id: 'field-' + Math.random().toString(36).substr(2, 9),
      type,
      label: 'New ' + type.charAt(0).toUpperCase() + type.slice(1),
      required: false,
      width: '1/1',
      choices: [FieldType.SELECT, FieldType.RADIO, FieldType.CHECKBOX, FieldType.QUIZ, FieldType.POLL, FieldType.SURVEY].includes(type) 
        ? [
            { id: 'c1', text: 'Option 1', value: 'opt1' },
            { id: 'c2', text: 'Option 2', value: 'opt2' },
            { id: 'c3', text: 'Option 3', value: 'opt3' }
          ]
        : undefined
    };

    setForm(prev => {
      const newPages = [...prev.pages];
      newPages[newPages.length - 1].fields.push(newField);
      return { ...prev, pages: newPages };
    });
    setSelectedFieldId(newField.id);
  };

  const handleUpdateField = (fieldId: string, updates: Partial<FormField>) => {
    setForm(prev => {
      const newPages = prev.pages.map(page => ({
        ...page,
        fields: page.fields.map(f => f.id === fieldId ? { ...f, ...updates } : f)
      }));
      return { ...prev, pages: newPages };
    });
  };

  const handleDeleteField = (fieldId: string) => {
    setForm(prev => ({
      ...prev,
      pages: prev.pages.map(page => ({
        ...page,
        fields: page.fields.filter(f => f.id !== fieldId)
      }))
    }));
    if (selectedFieldId === fieldId) setSelectedFieldId(null);
  };

  const handleExport = () => {
    const dataStr = JSON.stringify(form, null, 2);
    const blob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${form.title.toLowerCase().replace(/\s+/g, '-')}-config.json`;
    link.click();
  };

  const handleImport = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onload = (event) => {
        try {
          const config = JSON.parse(event.target?.result as string);
          setForm(config);
        } catch (err) {
          alert('Invalid form configuration file.');
        }
      };
      reader.readAsText(file);
    }
  };

  const allFields = form.pages.flatMap(p => p.fields);
  const selectedField = allFields.find(f => f.id === selectedFieldId);

  return (
    <div className="flex flex-col h-screen overflow-hidden bg-slate-50">
      <header className="h-16 bg-white border-b border-slate-200 flex items-center justify-between px-6 z-30 shrink-0">
        <div className="flex items-center gap-4">
          <div className="bg-indigo-600 p-2 rounded-lg text-white shadow-lg shadow-indigo-100">
            <LayoutGrid size={24} />
          </div>
          <div className="flex flex-col">
            <h1 className="text-xl font-bold text-slate-800 tracking-tight flex items-center gap-2 leading-none">
              Eagle Form <span className="text-[10px] font-black bg-indigo-100 text-indigo-700 px-2 py-0.5 rounded-full uppercase tracking-widest">Enterprise</span>
            </h1>
            <input 
              className="text-xs text-slate-400 bg-transparent border-none p-0 focus:ring-0 w-full mt-1 font-medium hover:text-slate-600 transition-colors"
              value={form.title}
              onChange={(e) => setForm({...form, title: e.target.value})}
            />
          </div>
        </div>

        <nav className="flex items-center gap-1 bg-slate-100 p-1 rounded-2xl border border-slate-200/50">
          {[
            { id: 'build', label: 'Builder' },
            { id: 'preview', label: 'Preview' },
            { id: 'entries', label: 'Entries' },
            { id: 'analytics', label: 'Analytics' },
            { id: 'settings', label: 'Settings' }
          ].map((tab) => (
            <button 
              key={tab.id}
              onClick={() => setActiveTab(tab.id as any)}
              className={`px-5 py-1.5 rounded-xl text-xs font-black uppercase tracking-widest transition-all ${activeTab === tab.id ? 'bg-white text-indigo-600 shadow-sm border border-slate-200/50' : 'text-slate-500 hover:text-slate-800'}`}
            >
              {tab.label}
            </button>
          ))}
        </nav>

        <div className="flex items-center gap-3">
          <div className="hidden lg:flex items-center gap-2 mr-4 border-r pr-4 border-slate-200">
            <button onClick={handleExport} title="Export Config" className="p-2 text-slate-400 hover:text-indigo-600 transition-colors bg-white rounded-lg border border-slate-100 shadow-sm">
              <Download size={18} />
            </button>
            <label className="p-2 text-slate-400 hover:text-indigo-600 transition-colors cursor-pointer bg-white rounded-lg border border-slate-100 shadow-sm">
              <UploadIcon size={18} />
              <input type="file" className="hidden" accept=".json" onChange={handleImport} />
            </label>
          </div>
          <button className="px-5 py-2.5 bg-indigo-600 text-white rounded-xl text-sm font-black uppercase tracking-widest hover:bg-indigo-700 shadow-xl shadow-indigo-100 transition-all hover:-translate-y-0.5 active:translate-y-0">
            Publish
          </button>
        </div>
      </header>

      <main className="flex-1 flex overflow-hidden">
        {activeTab === 'build' && (
          <>
            <BuilderSidebar onAddField={handleAddField} />
            <div className="flex-1 flex flex-col bg-slate-50 relative">
              <div className="h-12 bg-white border-b border-slate-200 flex items-center justify-between px-6 shrink-0">
                <div className="flex items-center gap-4 text-[10px] font-black text-slate-400 uppercase tracking-widest">
                  Canvas Workspace
                </div>
              </div>
              <div className="flex-1 overflow-y-auto p-8 custom-scrollbar">
                <BuilderCanvas 
                  form={form} 
                  selectedFieldId={selectedFieldId}
                  onSelectField={setSelectedFieldId}
                  onDeleteField={handleDeleteField}
                  onReorderFields={(fields) => setForm({...form, pages: [{...form.pages[0], fields}]})}
                />
              </div>
            </div>
            <FieldProperties 
              field={selectedField} 
              allFields={allFields}
              onUpdate={(updates) => handleUpdateField(selectedField!.id, updates)}
              onClose={() => setSelectedFieldId(null)}
            />
          </>
        )}

        {activeTab === 'preview' && (
          <div className="flex-1 flex flex-col items-center bg-slate-200 overflow-hidden">
            <div className="w-full bg-white/80 backdrop-blur-md border-b p-3 flex justify-center gap-4 sticky top-0 z-20">
              <button onClick={() => setPreviewDevice('desktop')} className={`p-2.5 rounded-xl transition-all ${previewDevice === 'desktop' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-500 hover:bg-slate-100'}`}><Monitor size={20} /></button>
              <button onClick={() => setPreviewDevice('tablet')} className={`p-2.5 rounded-xl transition-all ${previewDevice === 'tablet' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-500 hover:bg-slate-100'}`}><Tablet size={20} /></button>
              <button onClick={() => setPreviewDevice('mobile')} className={`p-2.5 rounded-xl transition-all ${previewDevice === 'mobile' ? 'bg-indigo-600 text-white shadow-lg' : 'text-slate-500 hover:bg-slate-100'}`}><Smartphone size={20} /></button>
            </div>
            <div className="flex-1 overflow-y-auto p-12 w-full flex justify-center custom-scrollbar">
              <div className={`transition-all duration-500 ease-out ${
                previewDevice === 'desktop' ? 'w-full max-w-5xl' : 
                previewDevice === 'tablet' ? 'w-[768px]' : 'w-[375px]'
              }`}>
                <div className="bg-white rounded-[2.5rem] shadow-[0_35px_60px_-15px_rgba(0,0,0,0.1)] p-16 min-h-[800px] border border-white">
                  <FormPreview 
                    form={form} 
                    onSubmit={(data) => {
                      const newEntry: FormEntry = {
                        id: 'entry-' + Date.now(),
                        formId: form.id,
                        data,
                        submittedAt: new Date().toISOString(),
                        ip: '127.0.0.1',
                        userAgent: navigator.userAgent
                      };
                      const newEntries = [newEntry, ...entries];
                      setEntries(newEntries);
                      localStorage.setItem('eagle_form_entries', JSON.stringify(newEntries));
                      alert('Submission successful!');
                    }}
                  />
                </div>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'entries' && (
          <DashboardEntries entries={entries} form={form} />
        )}

        {activeTab === 'analytics' && (
          <Analytics entries={entries} form={form} />
        )}

        {activeTab === 'settings' && (
          <FormSettings form={form} onUpdate={setForm} />
        )}
      </main>
    </div>
  );
};

export default App;
